import pyfirmata2

comport = 'COM3'
board = pyfirmata2.Arduino(comport)

segment_a = board.get_pin('d:2:o')
segment_b = board.get_pin('d:3:o')
segment_c = board.get_pin('d:4:o')
segment_d = board.get_pin('d:5:o')
segment_e = board.get_pin('d:6:o')
segment_f = board.get_pin('d:7:o')
segment_g = board.get_pin('d:8:o')

led_1=board.get_pin('d:9:o')
led_2=board.get_pin('d:10:o')
led_3=board.get_pin('d:11:o')
led_4=board.get_pin('d:12:o')
led_5=board.get_pin('d:13:o')

def clear_display():
    """Turn off all segments of the 7-segment display."""
    segment_a.write(0)
    segment_b.write(0)
    segment_c.write(0)
    segment_d.write(0)
    segment_e.write(0)
    segment_f.write(0)
    segment_g.write(0)
def led(fingerUp):
    if fingerUp==[0,0,0,0,0]:
        clear_display()
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(0)
        segment_b.write(1)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(1)
        segment_f.write(1)
        segment_g.write(1)
    elif fingerUp==[1,0,0,0,0]:#1
        led_1.write(1)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(0)
        segment_b.write(0)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
    elif fingerUp==[0,1,0,0,0]:
        led_1.write(0)
        led_2.write(1)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(0)
        segment_b.write(0)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
    elif fingerUp==[0,0,0,0,1]:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(1)
        segment_a.write(0)
        segment_b.write(0)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
    elif fingerUp==[0,1,1,0,0]: #2
        led_1.write(0)
        led_2.write(1)
        led_3.write(1)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(1)
        segment_f.write(1)
        segment_g.write(0) 
    elif fingerUp==[0,0,0,1,1]:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(1)
        led_5.write(1)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(1)
        segment_f.write(1)
        segment_g.write(0)
    elif fingerUp==[1,1,0,0,0]:
        led_1.write(1)
        led_2.write(1)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(1)
        segment_f.write(1)
        segment_g.write(0) 
      
    elif fingerUp==[0,1,1,1,0]:#3
        led_1.write(0)
        led_2.write(1)
        led_3.write(1)
        led_4.write(1)
        led_5.write(0)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(1)
        segment_g.write(1)
    elif fingerUp==[0,0,1,1,1]:
        led_1.write(0)
        led_2.write(0)
        led_3.write(1)
        led_4.write(1)
        led_5.write(1)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(1)
        segment_g.write(1)
    elif fingerUp==[1,1,1,0,0]:
        led_1.write(1)
        led_2.write(1)
        led_3.write(1)
        led_4.write(0)
        led_5.write(0)
        segment_a.write(1)
        segment_b.write(0)
        segment_c.write(1)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(1)
        segment_g.write(1)
    elif fingerUp==[0,1,1,1,1]:#4
        led_1.write(0)
        led_2.write(1)
        led_3.write(1)
        led_4.write(1)
        led_5.write(1)
        segment_a.write(1)
        segment_b.write(1)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
    elif fingerUp==[1,1,1,1,0]:
        led_1.write(1)
        led_2.write(1)
        led_3.write(1)
        led_4.write(1)
        led_5.write(0)
        segment_a.write(1)
        segment_b.write(1)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
    elif fingerUp==[1,1,0,1,1]:
        led_1.write(1)
        led_2.write(1)
        led_3.write(0)
        led_4.write(1)
        led_5.write(1)
        segment_a.write(1)
        segment_b.write(1)
        segment_c.write(0)
        segment_d.write(1)
        segment_e.write(0)
        segment_f.write(0)
        segment_g.write(1)
        
    elif fingerUp==[1,1,1,1,1]:
        led_1.write(1)
        led_2.write(1)
        led_3.write(1)
        led_4.write(1)
        led_5.write(1)
        segment_a.write(1)
        segment_b.write(1)
        segment_c.write(1)
        segment_d.write(0)
        segment_e.write(0)
        segment_f.write(1)
        segment_g.write(1)